/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package asignacion.conversionfr_cl;

import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class ConversionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConversionGUI
     */
    public ConversionGUI() {
        initComponents();
        this.setSize(410, 330); 
        this.setLocationRelativeTo(null);
        setTitle("Conversion de Grados");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        LbIcono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Lbvalor1 = new javax.swing.JLabel();
        Texvalor1 = new javax.swing.JTextField();
        Lbvalor2 = new javax.swing.JLabel();
        Texvalor2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo.setText("Conversion de Grados");
        jPanel1.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 32, -1, -1));

        LbIcono.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Escritorio\\MATERIAS_DE_ ITLA\\Cuarto_Cuatrimestre\\PROGRAMACION 1\\Programas\\PROGRAMA 4\\ConversionFr_Cl\\src\\main\\java\\asignacion\\conversionfr_cl\\imagenes\\sistema-del-icono-del-símbolo-de-celsius-y-de-fahrenheit-36794283.png")); // NOI18N
        jPanel1.add(LbIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 14, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbvalor1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Lbvalor1.setForeground(new java.awt.Color(0, 0, 0));
        Lbvalor1.setText("Fahrenheit");
        jPanel2.add(Lbvalor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Texvalor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Texvalor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Texvalor1KeyTyped(evt);
            }
        });
        jPanel2.add(Texvalor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, 30));

        Lbvalor2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Lbvalor2.setForeground(new java.awt.Color(0, 0, 0));
        Lbvalor2.setText("Celsius");
        jPanel2.add(Lbvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        Texvalor2.setEditable(false);
        Texvalor2.setBackground(new java.awt.Color(255, 255, 255));
        Texvalor2.setForeground(new java.awt.Color(0, 0, 0));
        Texvalor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(Texvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 110, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convertir");
        jButton1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jButton1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Escritorio\\MATERIAS_DE_ ITLA\\Cuarto_Cuatrimestre\\PROGRAMACION 1\\Programas\\PROGRAMA 4\\ConversionFr_Cl\\src\\main\\java\\asignacion\\conversionfr_cl\\imagenes\\3221897.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //validarCampos();
        conversionValores();
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Texvalor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Texvalor1KeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_Texvalor1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1PropertyChange

    private void jButton1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jButton1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1CaretPositionChanged
    
    private void validarCampos(){
        if(Texvalor1.getText().trim().length() <=0){
            
        }
    }
    private void conversionValores(){
        Fahre_Celsius convetir = new Fahre_Celsius();
        double celsius = convetir.conversion(Double.parseDouble(Texvalor1.getText()));
        Texvalor2.setText(celsius + "");
    }
    
    private void limpiarDatos(){
        Texvalor1.setText("");
        Texvalor2.setText("");
        Texvalor2.requestFocus();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConversionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbIcono;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel Lbvalor1;
    private javax.swing.JLabel Lbvalor2;
    private javax.swing.JTextField Texvalor1;
    private javax.swing.JTextField Texvalor2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
